.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Header: example.1,v 1.0 10/04/06 16:29:25 bent Exp $
.TH netsurfp 1 \" -*- nroff -*-
.SH NAME
netsurfp \- predict surface accessibility and secondary structure of protein
residues
.SH SYNOPSIS
.B netsurfp
[\fB-a\fP]
[\fB-c\fP \fI#\fP]
[\fB-d\fP \fIdatabase\fP]
[\fB-h\fP]
[\fB-i\fP \fIinfile\fP]
         [\fB-j\fP \fIsspfile\fP]
[\fB-k\fP]
[\fB-o\fP \fIoutfile\fP]
[\fB-s\fP \fIsyn_dir\fP]
         [\fB-t\fP \fIFASTA|HOW|PROF\fP]
[\fB-v\fP]  
[\fB-J\fP \fIsspoutfile\fP]

.SH DESCRIPTION
.B netsurfp
predicts the surface accessibility and secondary structure of residues in
amino acid sequences. For each residue the relative exposure is predicted
alongside the secondary structure; the reliability of the surface accessibility
prediction is stated in the form of a \fBZ\fP-score.

The method has been trained on more than 410,000 amino acid residues,
where 44.2% were classified as exposed. It was evaluated on an independent
dataset. The performance obtained was 79.0% correct prediction with a MCC
of 0.577 and PCC of 0.70. The method is described in detail in the reference
quoted below.

The input for the prediction is taken from \fIinfile\fP (\fB-i\fP) or, if no
file is specified, from \fIstdin\fP. The output will go to \fIstdout\fP by
default; it can also be printed to a file (\fB-o\fP).

The \fBnetsurfp\fP prediction process in in three steps:

1. Generation of alignment profiles: the input sequences are
   aligned to a non-redundant BLAST database. This step is
   not performed if the input contains profiles already (see
   \fBInput\fP below).

2. Prediction of the secondary structure. This step in not
   performed if the secondary structure of the input
   sequences is provided by the user (\fB\-j\fP).

3. Prediction of the surface accessibility. This step is
   always performed.

.B Input

The following input formats are supported (\fB-t\fP):

    \fBFASTA\fP (default)
    \fBHOW\fP
    \fBPROF\fP (Position Specific Scoring Matrix)

The \fBFASTA\fP and \fBHOW\fP formats are described on the manual pages for
those programs, respectively.

If the alignment profiles of the input sequences are already available
the \fBPROF\fP format should be used instead; it consists of lines
in the form:

.B "      1:"
Assignment B (buried) or E (exposed)
.br
.B "      2:"
Amino acid residue in one-letter code
.br
.B "      3:"
Sequence name
.br
.B "      4:"
Residue number
.br
.B "   5-24:"
Log-odds for the probabilities of the 20 amino
         acids on that position

A \fBPROF\fP file can be generated by \fBblastpgp\fP (see that software).

If a position specific scoring matrix is not provided by the user, it will
be generated by the
.B netsurfp
software in the course of the prediction process (see above, step 2).

The input sequences have to have unique identifiers. Special characters in the
identifiers will be replaced by the underscore characters ("_").

.B Output

The output is in columns, as follows:

.br
.B "   1:"
Class assignment - B (buried) or E (exposed),
.br
      see below
.br
.B "   2:"
Amino acid
.br
.B "   3:"
Sequence name
.br
.B "   4:"
Amino acid number
.br
.B "   5:"
Relative Surface Accessibility - RSA
.br
.B "   6:"
Absolute Surface Accessibility
.br
.B "   7:"
Z-fit score (RSA prediction only)
.br
.B "   8:"
Probability for alpha-helix
.br
.B "   9:"
Probability for beta-strand
.br
.B "  10:"
Probability for coil

The buried/exposed assignment has the threshold of 25% exposure, based on
the first layer networks and \fBnot\fP on RSA.

The secondary structure predictions (columns 8-10) are only included if
required specifically (\fB-a\fP).

The output can be made more verbose (\fB\-v\fP). All the reporting goes
to \fIstderr\fP.
.SH OPTIONS
.TP
.BI "\-a "
include the secondary structure prediction in the output. The default is not to
do this.
.TP
.BI "\-c" " #"
process # sequences in parallel. The default is 2. This option needs to be used
with caution as processing one sequence may employ several cpu:s depending of
the local setup.
.TP
.BI "\-d " 
path to local nr (non-redundant) blast database. For speed purposes nr70 can
be used.
.TP
.BI "\-h "
Show the allowed command line syntax and exit.
.TP
.BI "\-i" " infile"
The input file to process. If not specified, \fIstdin\fP will be used
instead. The format must be \fBFASTA\fP (default), \fBHOW\fP or \fBPROF\fP.
.TP
.BI "\-j" " sspfile"
use the secondary structure predictions in \fIsspfile\fP rather than the native
.B netsurfp
predictions.
.TP
.BI "\-k " 
keep all temporary directories. The default is not to do this.
.TP
.BI "\-o" " outfile"
Write the output to \fIoutfile\fP. If not specified \fIstdout\fP will be used.
.TP
.BI "\-s" " syndir"
The default location of the synapse file. Do not change this unless you know
what you are doing.
.TP
.BI "\-t" " format"
input file format. If the default \fBFASTA\f is not used, this option must be
given as either \fBHOW\fP or \fBPROF\fP (see above).
.TP
.B "\-v "
Verbose mode. All reporting will go to \fIstderr\fP.
.TP
.BI "\-J " " sspoutfile"
Generate an extra output file with the sequences and the secondary structure
predictions. The default is not to do this.
.SH EXAMPLES
.TP
 netsurfp -h 
this will show the help menu.
.TP
 netsurfp -i ./test/test.fasta 
a fasta file will be used as input, and rsa results will be written to stdout.
.TP
 netsurfp -i ./test/test.fasta -a
a fasta file will be used as input, and rsa results including secondary structure predictions will be written to stdout.
.TP
netsurfp -i ./test/test.prof -t PROF -a -v -k -o file.rsa
a \fBPROF\fP file will be used as input. Secondary structure predictions will be included in the result file, file.rsa, temp directories will be kept and verbose mode is on.

.SH VERSION
This manpage describes \fBnetsurfp\fP 1.0.

.SH REFERENCE
For publication of results, please cite:

A generic method for assignment of reliability scores applied to solvent
accessibility predictions.
.br 
Bent Petersen, Thomas Nordahl Petersen, Pernille Andersen, Morten Nielsen
and Claus Lundegaard.
.br 
\fBBMC Structural Biology\fP, 9:51, \fB2009\fP

The method is also available on-line at:

\fBhttp://www.cbs.dtu.dk/services/NetSurfP/\fP

.SH AUTHOR
Bent Petersen, bent@cbs.dtu.dk, April 2010.
.br
Last updated in April 2010 (v. 1.0).
.SH FILES
\fB/usr/cbs/bio/bin/netsurfp\fP           executable
.br
\fB/usr/cbs/bio/src/netsurfp-1.0\fP       software home
.SH SEE ALSO
\fBfasta\fP(1), \fBhow\fP(1)
